/**
 * G-code Export for 3D Printing
 * Generates G-code from 3D models for 3D printing
 */

import { ThreeDModel, ThreeDScene } from './threeManager';
import { BufferGeometry } from 'three';

export interface GCodeConfig {
  printer: 'fdm' | 'sla' | 'sls';
  layerHeight: number; // mm
  printSpeed: number; // mm/s
  travelSpeed: number; // mm/s
  nozzleTemperature: number; // °C
  bedTemperature: number; // °C
  infill: number; // 0-100%
  support: boolean;
  raft: boolean;
  skirt: boolean;
  brim: number; // lines
  retractionDistance: number; // mm
  retractionSpeed: number; // mm/s
}

export interface SliceLayer {
  layerNumber: number;
  z: number;
  contours: Array<Array<{ x: number; y: number }>>;
  infill: Array<Array<{ x: number; y: number }>>;
}

export class GCodeExporter {
  private config: GCodeConfig;

  constructor(config: Partial<GCodeConfig> = {}) {
    this.config = {
      printer: 'fdm',
      layerHeight: 0.2,
      printSpeed: 50,
      travelSpeed: 150,
      nozzleTemperature: 200,
      bedTemperature: 60,
      infill: 20,
      support: false,
      raft: true,
      skirt: false,
      brim: 0,
      retractionDistance: 2.0,
      retractionSpeed: 25,
      ...config
    };
  }

  exportToGCode(scene: ThreeDScene): string {
    let gcode = '';

    // G-code header
    gcode += '; G-code generated by CircuitCAD 3D Printer\n';
    gcode += `; Date: ${new Date().toISOString()}\n`;
    gcode += `; Printer: ${this.config.printer.toUpperCase()}\n`;
    gcode += `; Layer Height: ${this.config.layerHeight}mm\n`;
    gcode += `; Infill: ${this.config.infill}%\n\n`;

    // Initialize printer
    gcode += '; Initialize printer\n';
    gcode += 'G21 ; Set units to millimeters\n';
    gcode += 'G90 ; Use absolute coordinates\n';
    gcode += 'M82 ; Set extruder to absolute mode\n';
    gcode += `M104 S${this.config.nozzleTemperature} ; Set extruder temperature\n`;
    gcode += `M140 S${this.config.bedTemperature} ; Set bed temperature\n`;
    gcode += 'G28 ; Home all axes\n';
    gcode += 'G29 ; Auto bed leveling\n';
    gcode += `M109 S${this.config.nozzleTemperature} ; Wait for extruder temperature\n`;
    gcode += `M190 S${this.config.bedTemperature} ; Wait for bed temperature\n\n`;

    // Generate layers from 3D models
    const layers = this.sliceModels(scene.models);
    
    // Add raft if enabled
    if (this.config.raft) {
      gcode += this.generateRaft(layers[0]?.z || 0);
    }

    // Add brim if enabled
    if (this.config.brim > 0) {
      gcode += this.generateBrim();
    }

    // Add skirt if enabled
    if (this.config.skirt) {
      gcode += this.generateSkirt(layers[0]?.z || 0);
    }

    // Print layers
    layers.forEach((layer) => {
      gcode += `\n; Layer ${layer.layerNumber} at Z=${layer.z.toFixed(3)}mm\n`;
      
      // Move to layer height
      gcode += `G0 Z${layer.z.toFixed(3)} F${this.config.travelSpeed * 60}\n`;

      // Print perimeters
      layer.contours.forEach(contour => {
        gcode += this.printContour(contour, layer.z);
      });

      // Print infill
      if (layer.infill.length > 0) {
        gcode += '; Infill\n';
        layer.infill.forEach(line => {
          gcode += this.printInfillLine(line);
        });
      }
    });

    // Print supports if enabled
    if (this.config.support) {
      gcode += this.generateSupports();
    }

    // Finalize
    gcode += '\n; Finalize\n';
    gcode += 'G0 Z10 ; Lift nozzle\n';
    gcode += 'M104 S0 ; Turn off extruder\n';
    gcode += 'M140 S0 ; Turn off bed\n';
    gcode += 'G28 X Y ; Home X and Y\n';
    gcode += 'M84 ; Disable motors\n';

    return gcode;
  }

  private sliceModels(models: ThreeDModel[]): SliceLayer[] {
    const layers: SliceLayer[] = [];
    const minZ = 0;
    const maxZ = this.getMaxZ(models);
    const layerCount = Math.ceil((maxZ - minZ) / this.config.layerHeight);

    for (let i = 0; i < layerCount; i++) {
      const z = minZ + i * this.config.layerHeight;
      const layer: SliceLayer = {
        layerNumber: i,
        z,
        contours: [],
        infill: []
      };

      // Slice each model at this Z height
      models.forEach(model => {
        const contours = this.sliceModelAtZ(model, z);
        layer.contours.push(...contours);
      });

      // Generate infill
      if (i > 0) { // Skip first layer
        layer.infill = this.generateInfill(layer.contours);
      }

      layers.push(layer);
    }

    return layers;
  }

  private sliceModelAtZ(model: ThreeDModel, z: number): Array<Array<{ x: number; y: number }>> {
    const contours: Array<Array<{ x: number; y: number }>> = [];
    
    // Simplified slicing - in practice, this would intersect the 3D geometry with the plane
    // For now, we'll generate a simplified contour based on model bounds
    const geometry = model.geometry as BufferGeometry;
    
    if (geometry.attributes && geometry.attributes.position) {
      const positions = geometry.attributes.position;
      const contour: Array<{ x: number; y: number }> = [];

      // Find vertices at this Z height
      for (let i = 0; i < positions.count; i++) {
        const x = positions.getX(i);
        const y = positions.getY(i);
        const vertexZ = positions.getZ(i);

        if (Math.abs(vertexZ - z) < this.config.layerHeight / 2) {
          contour.push({ x, y });
        }
      }

      if (contour.length > 0) {
        contours.push(this.closeContour(contour));
      }
    }

    return contours;
  }

  private closeContour(points: Array<{ x: number; y: number }>): Array<{ x: number; y: number }> {
    // Close the contour by adding the first point at the end
    if (points.length > 0 && 
        (points[0].x !== points[points.length - 1].x || 
         points[0].y !== points[points.length - 1].y)) {
      return [...points, points[0]];
    }
    return points;
  }

  private generateInfill(contours: Array<Array<{ x: number; y: number }>>): Array<Array<{ x: number; y: number }>> {
    const infillLines: Array<Array<{ x: number; y: number }>> = [];

    if (contours.length === 0) return infillLines;

    // Simplified rectilinear infill
    const bounds = this.getBounds(contours);
    const spacing = 2.0; // mm (would be calculated based on infill percentage)

    // Generate infill lines
    for (let y = bounds.minY; y <= bounds.maxY; y += spacing) {
      const line: Array<{ x: number; y: number }> = [
        { x: bounds.minX, y },
        { x: bounds.maxX, y }
      ];
      infillLines.push(line);
    }

    return infillLines;
  }

  private getBounds(contours: Array<Array<{ x: number; y: number }>>): { minX: number; maxX: number; minY: number; maxY: number } {
    let minX = Infinity, maxX = -Infinity;
    let minY = Infinity, maxY = -Infinity;

    contours.forEach(contour => {
      contour.forEach(point => {
        minX = Math.min(minX, point.x);
        maxX = Math.max(maxX, point.x);
        minY = Math.min(minY, point.y);
        maxY = Math.max(maxY, point.y);
      });
    });

    return { minX, maxX, minY, maxY };
  }

  private getMaxZ(models: ThreeDModel[]): number {
    let maxZ = 0;

    models.forEach(model => {
      const geometry = model.geometry as BufferGeometry;
      if (geometry.attributes && geometry.attributes.position) {
        const positions = geometry.attributes.position;
        for (let i = 0; i < positions.count; i++) {
          const z = positions.getZ(i) * model.scale.z + model.position.y;
          maxZ = Math.max(maxZ, z);
        }
      }
    });

    return maxZ;
  }

  private generateRaft(z: number): string {
    let gcode = '\n; Raft\n';
    gcode += `G0 Z${(z - 0.3).toFixed(3)} F${this.config.travelSpeed * 60}\n`;
    gcode += 'G1 X10 Y10 E5 F' + (this.config.printSpeed * 60) + '\n';
    gcode += 'G1 X90 Y10 E5 F' + (this.config.printSpeed * 60) + '\n';
    gcode += 'G1 X90 Y90 E5 F' + (this.config.printSpeed * 60) + '\n';
    gcode += 'G1 X10 Y90 E5 F' + (this.config.printSpeed * 60) + '\n';
    gcode += 'G1 X10 Y10 E5 F' + (this.config.printSpeed * 60) + '\n';
    return gcode;
  }

  private generateBrim(): string {
    let gcode = '\n; Brim\n';
    // Simplified brim generation
    for (let i = 0; i < this.config.brim; i++) {
      gcode += `; Brim layer ${i + 1}\n`;
      // Would generate offset contours here
    }
    return gcode;
  }

  private generateSkirt(z: number): string {
    let gcode = '\n; Skirt\n';
    gcode += `G0 Z${z.toFixed(3)} F${this.config.travelSpeed * 60}\n`;
    gcode += 'G1 X5 Y5 E1 F' + (this.config.printSpeed * 60) + '\n';
    gcode += 'G1 X95 Y5 E1 F' + (this.config.printSpeed * 60) + '\n';
    gcode += 'G1 X95 Y95 E1 F' + (this.config.printSpeed * 60) + '\n';
    gcode += 'G1 X5 Y95 E1 F' + (this.config.printSpeed * 60) + '\n';
    gcode += 'G1 X5 Y5 E1 F' + (this.config.printSpeed * 60) + '\n';
    return gcode;
  }

  private printContour(contour: Array<{ x: number; y: number }>, z: number): string {
    let gcode = '; Perimeter\n';
    
    if (contour.length === 0) return gcode;

    // Move to first point
    gcode += `G0 X${contour[0].x.toFixed(3)} Y${contour[0].y.toFixed(3)} F${this.config.travelSpeed * 60}\n`;
    gcode += `G1 Z${z.toFixed(3)} E0 F${this.config.printSpeed * 60}\n`;

    // Print contour
    for (let i = 1; i < contour.length; i++) {
      const point = contour[i];
      const distance = this.distance(contour[i - 1], point);
      const extrusion = distance * 0.04; // Extrusion multiplier
      gcode += `G1 X${point.x.toFixed(3)} Y${point.y.toFixed(3)} E${extrusion.toFixed(4)} F${this.config.printSpeed * 60}\n`;
    }

    return gcode;
  }

  private printInfillLine(line: Array<{ x: number; y: number }>): string {
    if (line.length < 2) return '';

    let gcode = '';
    gcode += `G0 X${line[0].x.toFixed(3)} Y${line[0].y.toFixed(3)} F${this.config.travelSpeed * 60}\n`;

    const distance = this.distance(line[0], line[1]);
    const extrusion = distance * 0.04;
    gcode += `G1 X${line[1].x.toFixed(3)} Y${line[1].y.toFixed(3)} E${extrusion.toFixed(4)} F${this.config.printSpeed * 60}\n`;

    return gcode;
  }

  private generateSupports(): string {
    const gcode = '\n; Supports\n';
    // Simplified support generation
    // In practice, this would analyze overhangs and generate support structures
    return gcode;
  }

  private distance(p1: { x: number; y: number }, p2: { x: number; y: number }): number {
    return Math.sqrt(Math.pow(p2.x - p1.x, 2) + Math.pow(p2.y - p1.y, 2));
  }

  setConfig(config: Partial<GCodeConfig>): void {
    this.config = { ...this.config, ...config };
  }

  getConfig(): GCodeConfig {
    return { ...this.config };
  }
}

export const gcodeExporter = new GCodeExporter();

